# Generated by Django 2.2.1 on 2019-07-08 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'is_grupo_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nome_ou_destino', models.CharField(max_length=50, verbose_name='Nome ou Destino')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distância')),
                ('nivel', models.CharField(choices=[('1', 'Iniciante'), ('2', 'Médio'), ('3', 'Avançado')], max_length=1, verbose_name='Nível')),
                ('terreno', models.CharField(choices=[('1', 'Terra'), ('2', 'Asfalto'), ('3', 'Misto')], max_length=1, verbose_name='Tipo de Terreno')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('pago', models.BooleanField(default=False, verbose_name='Pedal pago?')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedais', to='grupos.Grupo', verbose_name='Grupo')),
                ('participantes', models.ManyToManyField(blank=True, related_name='pedais', to='usuarios.Profile', verbose_name='Lista de Participantes')),
            ],
            options={
                'verbose_name': 'Pedal',
                'verbose_name_plural': 'Pedais',
                'ordering': ('created',),
            },
        ),
    ]
