# Generated by Django 2.2.4 on 2019-09-04 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedal',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
