# Generated by Django 2.2.1 on 2019-07-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_grupo_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuarios.Profile', verbose_name='Admin'),
        ),
    ]
