# Generated by Django 2.2.4 on 2019-09-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20190904_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='encontro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Encontro'),
        ),
    ]
