# Generated by Django 2.2.4 on 2019-09-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_auto_20190925_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_grupo_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuarios.Profile', verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='grupos_que_participo', to='usuarios.Profile', verbose_name='Lista de Membros'),
        ),
    ]
